### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by zhaoyaogit** [physercoe/starquant#10]
python模块无法编译
from nanomsg import Socket, SUB, PUSH, SUB_SUBSCRIBE, SOL_SOCKET, RCVTIMEO
找不到方法：SUB, PUSH, SUB_SUBSCRIBE, SOL_SOCKET, RCVTIMEO 是为何？

**Comment by physercoe** [comment]
应该是nanomsg没有正确安装，先测试下nanomsg是否可以正常使用。
