### ISSUE TITLE
牛掰啊， 能否支持一下股票(A股)？

### ISSUE THREAD

**Issue by royburns** [physercoe/starquant#2]
RT

**Comment by physercoe** [comment]
股票有中泰xtp和宽睿oes接口，在开发测试中，这个需要专业投资者资格的。

**Comment by royburns** [comment]
嗯啊，这个了解，你这边加上逻辑就好了，到时候我改一下交易的部分就好了，我这边有实盘易

对了，希望股票这边能支持多标的 和 组合管理

谢谢

**Comment by physercoe** [comment]
没看懂“我这边加上逻辑”是什么意思，实盘易的接口是什么形式的我不太了解，有对应的sdk开发包和接口文件吗？如果用这套框架那得先了解这个框架，一般不是简单的几十行代码可以搞定的。

多标的实盘稍微改下strategy manager（strategyengine）就行，多标的回测也有，因为有人定制了，暂时就不方便push上去，自己改也行，相对单标的就是增加个字典存储每个标的的信息。

组合管理不确定你指的具体意思是什么，操作上要做什么事情。

**Comment by royburns** [comment]
嗯，我先看看代码
