### ISSUE TITLE
能否提供windows平台的第三方依赖库

### ISSUE THREAD

**Issue by royburns** [physercoe/starquant#3]
你有用windows吗，我这边配置有问题，编译不过，能否提供windows平台的第三方依赖库

**Comment by physercoe** [comment]
实盘还是回测？
实盘比较麻烦，涉及到的库比较多，可以看下CMakelists.txt里的依赖，本人不在windows下实盘，故要弄的话要自己折腾一下了。。。
回测的话主要是python的库，比较容易，anaconda装好，再把vnpy需要的库装上就差不多了，因为回测是基于vnpy重构的，其他的根据报错信息处理就行。

**Comment by royburns** [comment]
ok，了解了，主要是回测吧，暂时不上实盘

**Comment by physercoe** [comment]
恩，遇到解决不了的实际问题可以再提issue，我看看是什么问题。
