### ISSUE TITLE
配置文件缺失

### ISSUE THREAD

**Issue by royburns** [physercoe/starquant#4]
config_server.yaml is missing
config_client.yaml is missing

![image](https://user-images.githubusercontent.com/652375/65603241-e259a800-dfd7-11e9-84f3-a8bc26cfa72c.png)

**Comment by physercoe** [comment]
配置文件自己先看代码写下吧，实在弄不出来给我发个邮件，我给个样本。之所以不放配置文件，是希望能交流一下代码相关框架和设计等思想，抛砖引玉，学习提高，不枉开源代码～

**Comment by royburns** [comment]
嗯嗯，好的，我先自己折腾一下

**Comment by keel1982** [comment]
> 嗯嗯，好的，我先自己折腾一下

您好，配置文件折腾出来了吗？能不能发给我一份？ keel1982@gmail.com 谢谢！
