### ISSUE TITLE
windows环境

### ISSUE THREAD

**Issue by archangellin** [physercoe/starquant#5]
咨询下，windows环境下，vs2015 安装完都还需要安装哪些部件？

**Comment by physercoe** [comment]
实盘需要(c++)：
boost 
nanomsg 1.1.5
log4cplus 2.04
yamlcpp
libmongoc-1.0
fmt5.3
目前的实盘测试都是在阿里云/腾讯云的Ubuntu18.04或manjaro18系统进行的，已经运行3个多月，windows没有充分实盘测试过。

回测(基于python)先安装anaconda3,然后安装 
mongoengine,
ta-lib,
deap,
peewee
pymysql
psycopg2
rqdatac(非必须)
nanomsg(非必须)
