### ISSUE TITLE
请求安装文档

### ISSUE THREAD

**Issue by zhihuba** [physercoe/starquant#6]
rt 
系统版本 `Ubuntu 18.0.4`
软件版本 `dev or releases`
均提示 `Could not find a package configuration file provided by "libmongoc-1.0"`
尝试的方法`sudo apt-get install libmongoc-1.0-0
sudo  apt-get install libmongoc-dev
sudo  apt-get install libbson-dev
sudo  apt-get install libbson-1.0-0`
在CMakeLists 增加 ` include_directories("/usr/include/libmongoc-1.0")
 include_directories("/usr/include/libbson-1.0")`

**Comment by physercoe** [comment]
这个仔细看下报错就能找到问题。
安装文档等star数量到一定量时再考虑。
以后不会回答没有star的用户提问，没有义务也没有时间。

**Comment by physercoe** [comment]
可以看下ubuntu18.04 里libmongoc默认的安装路径（头文件和库文件）在哪，我记得在阿里云/腾讯云18.04上安装时库文件不是在/usr/lib下，为此当时还改了一下libmongoc/libbson对应cmake的库文件路径设置，具体可以根据报错的提示来改。

**Comment by zhihuba** [comment]
尝试过 修改cmake 链接库位置的 依旧过不去

**Comment by physercoe** [comment]
具体报什么错？怎么改的？没有完整具体的信息，我也无能为力。

**Comment by physercoe** [comment]
另外cmake会在其默认的路径里寻找**.cmake文件，即package configuration file，libmongoc对应的libmongoc-1.0-config.cmake要看下装到哪了，要让cmake找到。

**Comment by zhihuba** [comment]
谢谢,我去尝试下
